Epoch: 0
Traceback (most recent call last):
  File "C:\Users\Srikrishnan\AppData\Local\Temp\ipykernel_2116\2969065933.py", line 46, in train_wandb
    loss, accuracy = optimizer.gradient_descent(model, x, y, i)
  File "C:\Users\Srikrishnan\AppData\Local\Temp\ipykernel_2116\661297437.py", line 21, in gradient_descent
    output, loss, acc = model(x,y)
  File "C:\Users\Srikrishnan\AppData\Local\Temp\ipykernel_2116\1723096026.py", line 64, in __call__
    self.loss = self.loss_fn(x, y) + self.alpha * (self.squared_weights_sum + self.squared_bias_sum) / 2    # L2 regularization loss term
  File "C:\Users\Srikrishnan\AppData\Local\Temp\ipykernel_2116\1462165583.py", line 8, in __call__
    return np.mean(self.cross_entropy(y_true, y_pred))
  File "C:\Users\Srikrishnan\AppData\Local\Temp\ipykernel_2116\1462165583.py", line 15, in cross_entropy
    return -np.log(np.sum(y_true*y_pred, axis=1))
ValueError: operands could not be broadcast together with shapes (64,10) (64,)
