Traceback (most recent call last):
  File "D:\IITM\DA6401\train.py", line 203, in <module>
    main()
  File "D:\IITM\DA6401\train.py", line 130, in main
    train, valid, test = load_fashion_mnist()
TypeError: load_fashion_mnist() missing 1 required positional argument: 'batch_size'
Traceback (most recent call last):
  File "D:\IITM\DA6401\train.py", line 203, in <module>
    main()
  File "D:\IITM\DA6401\train.py", line 130, in main
    train, valid, test = load_fashion_mnist()
TypeError: load_fashion_mnist() missing 1 required positional argument: 'batch_size'
